"""Head-to-head: which reader should read a Fakturama grid?

    python3 tools/bench_readers.py

Runs the same grid images through every configured provider and through the
local OCR, times each, and scores it against a known-correct reading. Writes
docs/BENCHMARK.md.

The question is not "which OCR is best" in the abstract. It is narrower and
more useful: these are crisp, machine-rendered tables at 1:1, so nobody is
going to misread a glyph. What separates the options is whether they return
the table's STRUCTURE -- which cell belongs to which column -- and how long
they take to do it.
"""

from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.run import load_env  # noqa: E402

#: Images with a reading a human has checked. Kept small on purpose: the point
#: is structure, not glyph accuracy, and a wrong column is a wrong record.
CASES = [
    {
        "image": "docs/screenshots/dbg-items.png",
        "what": "the VATs list, 4 columns, 1 row",
        "columns": ["Standard", "Name", "Description", "Value"],
        "must_contain": ["VAT 19%", "19.00"],
    },
    {
        "image": "docs/bench/address-grid.png",
        "what": "the address picker, 8 columns, 1 row",
        "columns": ["No.", "First Name", "Name", "Company", "ZIP", "City"],
        "must_contain": ["CUST000001", "Marta", "Klein", "10117", "Berlin", "BILLING"],
    },
]


def score(got: dict, case: dict) -> tuple[int, int, str]:
    """(columns matched, values found, note). Exact on columns, substring on values."""
    raw = got.get("columns", [])
    cols = [str(c.get("name", "") if isinstance(c, dict) else c).strip() for c in raw]
    want_cols = case["columns"]
    matched = sum(1 for w in want_cols
                  if any(w.lower().rstrip(".") == c.lower().rstrip(".") for c in cols))

    flat = json.dumps(got).lower()
    found = sum(1 for v in case["must_contain"] if v.lower() in flat)
    return matched, found, f"{len(cols)} cols, {len(got.get('rows', []))} rows"


def run_one(reader, case: dict) -> dict:
    img = Path(case["image"])
    t0 = time.monotonic()
    try:
        got = reader(img)
        dt = time.monotonic() - t0
        m, f, note = score(got, case)
        return {"ms": int(dt * 1000), "cols": m, "vals": f, "note": note, "error": None}
    except Exception as exc:
        return {"ms": int((time.monotonic() - t0) * 1000), "cols": 0, "vals": 0,
                "note": "", "error": f"{type(exc).__name__}: {exc}"}


def main() -> None:
    load_env()
    from src import vision

    readers: list[tuple[str, object]] = []

    provs = vision.providers()
    for i, p in enumerate(provs):
        host = p["base"].split("//")[-1].split("/")[0]
        for model in p["models"][:2]:
            def make(model=model, p=p):
                def r(img: Path):
                    return vision._read_table_via(img, p, model) if hasattr(vision, "_read_table_via") \
                        else _via(vision, img, p, model)
                return r
            readers.append((f"{host}  {model}", make()))

    try:
        from src import ocr
        if ocr.available():
            readers.append(("local rapidocr (no account)", lambda img: ocr.read_table(img)))
        else:
            print("note: rapidocr not installed here; run this on the VM for the local row")
    except Exception as exc:
        print("note: local OCR unavailable:", exc)

    missing = [c["image"] for c in CASES if not Path(c["image"]).exists()]
    if missing:
        print("missing benchmark images:", missing)
        return

    rows = []
    for name, reader in readers:
        per = [run_one(reader, c) for c in CASES]
        ok_cols = sum(r["cols"] for r in per)
        want_cols = sum(len(c["columns"]) for c in CASES)
        ok_vals = sum(r["vals"] for r in per)
        want_vals = sum(len(c["must_contain"]) for c in CASES)
        ms = sum(r["ms"] for r in per) // max(1, len(per))
        err = next((r["error"] for r in per if r["error"]), None)
        rows.append({"name": name, "cols": f"{ok_cols}/{want_cols}",
                     "vals": f"{ok_vals}/{want_vals}", "ms": ms, "error": err})
        print(f"{name:52} cols {ok_cols}/{want_cols}  values {ok_vals}/{want_vals}  {ms:>6}ms"
              + (f"  {err}" if err else ""))

    Path("docs").mkdir(exist_ok=True)
    out = ["# Which reader should read the grid?", "",
           "Generated by `tools/bench_readers.py`. Same images, same prompt, "
           "scored against a reading a human checked.", "",
           "| Reader | Columns | Values | Avg per grid |", "|---|---|---|---|"]
    for r in sorted(rows, key=lambda r: (-int(r["cols"].split("/")[0]), r["ms"])):
        note = f" — {r['error']}" if r["error"] else ""
        out.append(f"| `{r['name']}` | {r['cols']} | {r['vals']} | {r['ms']} ms{note} |")
    Path("docs/BENCHMARK.md").write_text("\n".join(out) + "\n")
    print("\nwrote docs/BENCHMARK.md")


def _via(vision, img: Path, p: dict, model: str) -> dict:
    """Call one provider+model directly, bypassing the failover chain."""
    saved = {k: os.environ.get(k) for k in ("LLM_BASE_URL", "LLM_API_KEY", "LLM_MODEL",
                                            "LLM_FALLBACK_MODELS")}
    try:
        os.environ["LLM_BASE_URL"] = p["base"]
        os.environ["LLM_API_KEY"] = p["key"]
        os.environ["LLM_MODEL"] = model
        os.environ["LLM_FALLBACK_MODELS"] = ""
        vision._TABLE_CACHE.clear() if hasattr(vision, "_TABLE_CACHE") else None
        return vision.read_table(img)
    finally:
        for k, v in saved.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v


if __name__ == "__main__":
    main()
